# Generated by Django 4.0.4 on 2022-05-31 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField()),
                ('years_of_experience', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('F', 'Finance')], max_length=64)),
                ('resume', models.FileField(null=True, upload_to='candidates_resumes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
